export { default as GitHubIcon } from './github'
export { default as InstagramIcon } from './instagram'
export { default as LinkdinIcon } from './linkedin'
export { default as LogoIcon } from './logo'
export { default as TwitterIcon } from './twitter'
export { default as ExternalLinkIcon } from './external'
export { default as LoadingIcon } from './loading'
export { default as Icon } from './icon'
